name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include: [ "*" ]
  paths:
    exclude: [ "README.md" ]

jobs:
  - job: docker_ci
    displayName: "Docker CI"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 10

    steps:
    - checkout: 'self'
      clean: true
      submodules: 'recursive'

    - bash: |
        docker build --tag jamesits/smsgateway:latest .
      displayName: 'Build'

  - job: python_ci
    displayName: "Python CI"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 10
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
    - checkout: 'self'
      clean: true
      submodules: 'recursive'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - bash: |
        sudo -EH env "PATH=$PATH" python3 -m pip install --upgrade pip setuptools mypy flake8 pytest pytest-cov
      displayName: 'Install dependencies'

    - bash: |
        sudo -EH env "PATH=$PATH" python3 setup.py install
      displayName: 'Install package'

    - bash: |
        mypy .
      displayName: 'Mypy check'
      continueOnError: true

    - script: |
        flake8 .
      displayName: 'flake8 check'
      continueOnError: true

    - script: |
        pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      displayName: 'pytest check'
      continueOnError: true