[general]
log_level = 1 # 1: debug 2: info

[[listener.SMTP]]
ip = "0.0.0.0"
port = 25

[[listener.SMTP]]
ip = "::"
port = 25

[[listener.DbltekSmsListener]]
ip = "0.0.0.0"
port = 44444

[[listener.SMPPListener]]

[[device]]
vendor = "dbltek"
model = "GoIP8"
connector = "smtp"
ip = "100.97.1.7"
match_mode = "equal"
username = "test-goip@example.com"
password = "114514"
timezone = +8
route = [
    "smtp1"
]

[[device]]
vendor = "dbltek"
model = "GoIP8"
connector = "dbltek_sms_server"
ip = "100.97.1.7"
match_mode = "equal"
username = "goip-1"
password = "goip"
timezone = +8
route = [
    "smtp1"
]

[[device]]
vendor = "synway"
model = "SMG4008-8LC"
connector = "SMPP"
ip = "100.97.1.13"
port = 2775
username = "YajuuSenpai"
password = "114514"
match_mode = "equal"
route = [
    "smtp1"
]

[[route]]
alias = "smtp1"
connector = "smtp"
server = "smtp.example.com"
port = 25
username = "test@example.com"
password = "114514"
from_address = "test@example.com"
to_address = "test@example.com"