[general]
# log level
# 1: debug; 2: info; 3: warning
# alert: setting log_level to 1 will cause credentials being printed in the log.
log_level = 2

[routes]
# routes
# listener -> source [-> filter] -> sink

"smpp_1" = [
    "smg4008_1"
]

"smg4008_1" = [
    "default_mail",
    "telegram_1",
]

# a SMPP client
[[listener]]
alias = "smpp_1"
type = "smpp"

[[source]]
alias = "smg4008_1"
type = "smpp"
vendor = "synway"
model = "SMG4008-8LC"
ip = "192.168.1.102"
port = 2775
username = "smpp_username"
password = "smpp_password"

[[sink]]
alias = "default_mail"
type = "smtp"
server = "smtp.example.com"
port = 465
encryption = 'tls'
username = "smtp_user@example.com"
password = "smtp_password"
from_address = "smtp_user@example.com"
to_address = "your_email@example.com"

[[sink]]
alias = "telegram_1"
type = "telegram-bot"
token = "your_bot_token"
chat_id = 12345678